name: CI Nuget

on:
  push:
    branches:
    - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Set VERSION variable from latest tag (if existing) plus date and commit
      run: | 
        LATEST_TAG=$(git ls-remote --tags origin | tail -n 1 | awk '{ print $2; }' | sed 's/.*v//')
        echo "LATEST_TAG: ${LATEST_TAG}"
        LATEST_TAG=${LATEST_TAG:=0.0.1}
        VERSION=${LATEST_TAG}-next.$(date +%Y%m%d).${GITHUB_RUN_NUMBER}
        echo "VERSION: ${VERSION}" 
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Set SOLUTION variable to point to solution file
      run: |
        SOLUTION=$(find . -name '*.sln' -printf "%p" -quit)
        echo "SOLUTION: ${SOLUTION}"
        echo "SOLUTION=${SOLUTION}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} ${SOLUTION}

    - name: Pack with debug symbols
      run: dotnet pack --configuration Release /p:Version=${VERSION} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output . ${SOLUTION}

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: package
        path: '*.*nupkg'

  push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

    - name: Download artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: package

    - name: Push to NuGet
      run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/${GITHUB_REPOSITORY%/*}/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
